	[lists.bedrockoid]
		disableSnowUnderTreesIn = []

	[flags.bedrockoid]
		entitySharesFire = true
		fallenTrees = true
		armorStandArms = true
		frostwalkerBoost = true
		canPlantsBeBonemeal = true
		reachAroundPlacement = true
		snowSpawnsUnderTrees = true
		cauldronNaturalFilling = true
		wetSpongesDryOut = true
		shieldActivatesWhenSneaking = true
		blocksWaterloggability = true
		snowCoversVines = true
		stopElytraByPressingSpace = true
		shulkersCanBeDyed = true
		canSugarcaneBeBonemeal = true
		snowlogging = true
		fireAspectImprovements = true
		snowCoversLeaves = true
		sodiumTurnOffSnowloggability = false
		composterCollisionFix = true
		redstoneConnectsToPiston = true
		sheepFurColorFix = true
