#Friends
[friend_settings]
	#A list of users who can be chosen when it spawns a distant friend. 
	#Format: "<username>", "<username>,<texture_location/body_type>" or "<username>,<texture_location/body_type>,<body_type>"
	#Example: "darkosto" or "darkosto,minecraft:entity/player/slim/noor,slim"
	friends = ["darkosto", "shynieke", "mrbysco"]
	#A list of dimensions where distant friends can spawn, using their resource location. 
	#Format: "<namespace>:<path>"
	#Example: "minecraft:overworld" or "minecraft:the_nether"
	spawnDimensions = ["minecraft:overworld"]
	#Add the players from the whitelist to the Friends list [default: true]
	addWhitelistPlayers = true
	#Show the name of the friend above their head [default: true]
	showName = true

#Compat
[compat_settings]
	#Add players from a Player Mobs whitelist to the Friends list [default: false]
	playerMobsCompat = false
	#The player mobs Name Links, must start with https://whitelist.gorymoon.se
	playerMobsNameLinks = []
