{
  "DurabilityWoodenExcavator": 302,
  "DurabilityStoneExcavator": 650,
  "DurabilityCopperExcavator": 850,
  "DurabilityIronExcavator": 1300,
  "DurabilityGoldExcavator": 750,
  "DurabilityLapisExcavator": 1100,
  "DurabilityRedstoneExcavator": 1100,
  "DurabilityObsidianExcavator": 11200,
  "DurabilityDiamondExcavator": 8025,
  "DurabilityEmeraldExcavator": 9768,
  "DurabilityNetheriteExcavator": 13675,
  "radiusWoodenExcavator": 1,
  "radiusStoneExcavator": 1,
  "radiusCopperExcavator": 1,
  "radiusIronExcavator": 1,
  "radiusGoldExcavator": 1,
  "radiusLapisExcavator": 1,
  "radiusRedstoneExcavator": 1,
  "radiusObsidianExcavator": 1,
  "radiusDiamondExcavator": 1,
  "radiusEmeraldExcavator": 1,
  "radiusNetheriteExcavator": 1
}