{
  "DurabilityWoodenHammer": 302,
  "DurabilityStoneHammer": 650,
  "DurabilityCopperHammer": 850,
  "DurabilityIronHammer": 1300,
  "DurabilityGoldHammer": 750,
  "DurabilityLapisHammer": 1100,
  "DurabilityRedstoneHammer": 1100,
  "DurabilityObsidianHammer": 11200,
  "DurabilityDiamondHammer": 8025,
  "DurabilityEmeraldHammer": 9768,
  "DurabilityNetheriteHammer": 13675,
  "radiusWoodenHammer": 1,
  "radiusStoneHammer": 1,
  "radiusCopperHammer": 1,
  "radiusIronHammer": 1,
  "radiusGoldHammer": 1,
  "radiusLapisHammer": 1,
  "radiusRedstoneHammer": 1,
  "radiusObsidianHammer": 1,
  "radiusDiamondHammer": 1,
  "radiusEmeraldHammer": 1,
  "radiusNetheriteHammer": 1
}